### ISSUE TITLE
Too buggy to be usable.

### ISSUE THREAD

**Issue by kray42** [kivy/kivy-designer#105]
First the good part. This software installs and runs well on windows7, no problems there.

The problem is that it cannot be used seriously and crashes quite often. 
It could be that I am not using it properly, but then no documentation like Tutorial or User Guide exists.
Selecting help from the menu also crashes the app.

**Comment by kived** [comment]
While we welcome detailed reports of individual bugs, just stating that it is not usable is not productive. This is alpha software and not meant to be production ready. Please feel free to submit individual issues for each bug you have experienced including a traceback (if applicable) and details about how you triggered the bug.
