### ISSUE TITLE
Widgets can't be dragged in templates

### ISSUE THREAD

**Issue by dessant** [kivy/kivy-designer#126]
I'm trying to drag a button in the BoxLayout template for example, but it does not show up, and there is an exception:

```python
File "e:\dev\prs\kivy-designer\designer\playground.py", line 327, in on_touch_up
    if self.child.parent != self:

AttributeError("'NoneType' object has no attribute 'parent'",)
```

**Comment by kiok46** [comment]
Same error here!

**Comment by Tomis1** [comment]
The same error :(

**Comment by aron-bordin** [comment]
Are you using Python 3?
I'm working in this bug, and I'll probably push the fix until the end of the week. Here I can reproduce only on py3. Can someone confirm it?

**Comment by Tomis1** [comment]
yes, i'm using python 3.4 on windows 10 and on raspberry isn't possible to
start it (last Error is> TypeError: create_window() takes exactly 1
argument (2 given) - only for half second will be the first window(open or
new project window) showed .
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Tento
email byl odeslán z počítače bez virů, chráněného programem Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-14 23:40 GMT+01:00 Aron Barreira Bordin <notifications@github.com>:

**Comment by aron-bordin** [comment]
There is an open issue about this problem with raspberry: https://github.com/kivy/kivy-designer/issues/152
I'll try to check it asap

**Comment by hambi-hemts** [comment]
I have the same problem like @dessant

**Comment by aron-bordin** [comment]
Hi all,
bug fixed in master.

Thx
