### ISSUE TITLE
Error while running main.py

### ISSUE THREAD

**Issue by kiok46** [kivy/kivy-designer#133]
This is the traceback I get when I try to run main.py file. 

`Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/home/kiok/Documents/Kivy-designer/ready/kivy-designer-master/designer/app.py", line 52, in <module>
     from designer.designer_content import DesignerContent
   File "/home/kiok/Documents/Kivy-designer/ready/kivy-designer-master/designer/designer_content.py", line 11, in <module>
     from designer.buildozer_spec_editor import BuildozerSpecEditor
   File "/home/kiok/Documents/Kivy-designer/ready/kivy-designer-master/designer/buildozer_spec_editor.py", line 14, in <module>
     from pygments.lexers.configs import IniLexer
 ImportError: No module named configs`

I used `sudo pip install -U pygments` command to install pygments.
I have installed Pygments 1.6. (latest)
Installed at ` /usr/lib/python2.7/dist-packages`, owned by OS.

Thanks.

**Comment by aron-bordin** [comment]
Hi @kiok46 !

The current version of pygments is 2.0.2.

Please, update your package and reopen this issue if the problem persists.

**Comment by kiok46** [comment]
That was an internal problem. It wasn't upgrading, I had to remove and then reinstall it again.
I used this command to make it work.
`sudo rm -rf /usr/lib/python2.7/dist-packages/Pygments-1.6.egg-info`
Thanks :)

**Comment by AFAgarap** [comment]
![screenshot from 2016-02-27 19 01 31](https://cloud.githubusercontent.com/assets/11130276/13372599/968cfbb0-dd84-11e5-824c-a17c93c02867.png)
Same problem here. Can't resolve it. Already tried upgrading pygments, but it said "Requirement already up-to-date: pygments in /usr/local/lib/python2.7/dist-packages"

**Comment by sshivaji** [comment]
The solution before this worked for me - sudo rm -rf /usr/lib/python2.7/dist-packages/

To debug the issue. Open "python" and then "import pygments" followed by "pygments.__version__" and "pygments.__file__". That folder needs to be deleted

**Comment by AFAgarap** [comment]
Thank you very much, @sshivaji! It now works, a bit slow though.

![screenshot from 2016-03-13 09 55 01](https://cloud.githubusercontent.com/assets/11130276/13726440/14639f70-e902-11e5-9fe9-5ada75d49563.png)
