### ISSUE TITLE
Kivy-designer should ask whether or not to save the newly created project.

### ISSUE THREAD

**Issue by kiok46** [kivy/kivy-designer#150]
If I create a new project and make some edits or create some new files but close kivy-designer without saving the project somewhere, then KD won't show any warnings or ask something like this. 

    Your new project is not saved anywhere and all the work done will be lost, 
    would you like to save it? | Yes || No |

**Comment by kiok46** [comment]
@aron-bordin  I can fix it, if you like.

**Comment by aron-bordin** [comment]
sure, go ahead :)

**Comment by aron-bordin** [comment]
check: https://github.com/kivy/kivy-designer/pull/73/files

the on_request_close checks the `self._curr_proj_changed` variable

looks like that this variable is not being changed.
