### ISSUE TITLE
I can't open kivy-designer on Windows 10

### ISSUE THREAD

**Issue by six3six** [kivy/kivy-designer#161]
I wan't to open kivy-designer PowerShell but I can't because I have a exception

http://pastebin.com/rCHx85ND

And it's the same on CMD

**Comment by aron-bordin** [comment]
Hi @six3six 
Are you able to run Kivy apps on your env?
I tested it here, and I got the same error due to this bug: https://github.com/kivy/kivy/pull/3888
Updating to kivy master solved my problem. Please, check if it helps, re-open this issue if the problem persists.
