### ISSUE TITLE
Exception Overflow when resizing on MacOS

### ISSUE THREAD

**Issue by chevdor** [kivy/kivy-designer#174]
Hello,

When I open the designer, I can see the UI but rather small.
As soon as I enlarge the window, I get a bunch of:

     Exception OverflowError: 'signed integer is greater than maximum' in 'kivy.graphics.context.Context.dealloc_texture' ignored

Reducing the window again does not solve the issue.
To 'solve' the issue, I need to resize the window to something real small.
Then it start with the following warning:

     [WARNING] [Accordion   ] not enough space for displaying all children
     [WARNING] [Accordion   ] need 176px, got 100px

**Comment by mksmsrkn** [comment]
Hey @chevdor , could you solve that issue. Currently have the same problem, and that's the only place google could find. Seems that's not so common problem.

**Comment by chevdor** [comment]
Nop unfortunately. I was on IRC and the answer I got was that this would
probably never be fixed. It sounded like an 'uninteresting' bug that none
really cared about.

Too bad as it makes the software rather unusable. The only workaround I
found is that if you resize (only the outside window will grow), then close
the program and reopen, then all will fit the size you previously set.
Definitely not convenient but that´s all I have.

**Comment by mksmsrkn** [comment]
Ohh, that's bad. Just found this framework and such a problem arises.
Well, I will try to figure out a way to solve it, if I get something will share it.
Thanks for quick response.

**Comment by mksmsrkn** [comment]
Seem like development version (1.9.2) doesn't have that bug.
Followed instructions [here](https://kivy.org/docs/installation/installation.html#development-version) to install it. Worked for me.

**Comment by chevdor** [comment]
oh great, thanks for sharing, I will give it a shot then.

**Comment by robverhoef** [comment]
I'm a Python n00b,  so maybe it's just me. But I still see this error in 1.9.2 after copy pasting an example from https://kivy.org/docs/guide/basic.html:

[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v3.5.2 (default, Jan 14 2017, 21:15:01)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_pygame, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.22.25'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel Iris OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Context     ] Reloading graphics data...
[INFO   ] [Context     ] Reloading done in 0.0280s
 Exception ignored in: 'kivy.graphics.context.Context.dealloc_texture'
 OverflowError: signed integer is greater than maximum
