### ISSUE TITLE
ImportError: No module named configs

### ISSUE THREAD

**Issue by AFAgarap** [kivy/kivy-designer#192]
![screenshot from 2016-02-27 19 01 31](https://cloud.githubusercontent.com/assets/11130276/13372606/d94c0a4a-dd84-11e5-8fd1-fc3505bed664.png)

I can't get kivy designer to work. Please help. Thank you!

**Comment by AFAgarap** [comment]
![screenshot from 2016-02-27 19 05 45](https://cloud.githubusercontent.com/assets/11130276/13372610/1f319fde-dd85-11e5-8026-126cb21b7314.png)

Tried upgrading the pygments, still nothing.

**Comment by aron-bordin** [comment]
Hi!

Try to force the pygments installation, maybe you get some problem while installing.

`sudo pip install -I pygments`

and if possible, give me some feedback.

**Comment by AFAgarap** [comment]
Still the same problem.

![screenshot from 2016-02-28 09 13 02](https://cloud.githubusercontent.com/assets/11130276/13376616/7d9597f8-ddfb-11e5-84f4-bc022d54a857.png)

**Comment by AFAgarap** [comment]
Already solved this, got the answer from another thread: #133 
Thanks anyway! :+1:
