### ISSUE TITLE
Can't run on Mac OS X

### ISSUE THREAD

**Issue by antkowiakit** [kivy/kivy-designer#199]
Hello I have problem, when I run I get black screen Here is log:

> ➜  kivy-designer git:(master) python3 main.py
> [INFO   ] [Logger      ] Record log in /Users/patryk/.kivy/logs/kivy_16-03-10_14.txt
> [INFO   ] [Kivy        ] v1.9.2-dev0
> [INFO   ] [Python      ] v3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
> [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
> [INFO   ] [Factory     ] 182 symbols loaded
> [INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
> [INFO   ] [Text        ] Provider: pygame
> [INFO   ] [Window      ] Provider: pygame
> [ERROR  ] [WinPygame   ] unable to set icon
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/core/window/window_pygame.py", line 215, in set_icon
>     self._set_icon_standard(filename)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/core/window/window_pygame.py", line 227, in _set_icon_standard
>     im = pygame.image.load(filename)
> pygame.error: File is not a Windows BMP file
> [INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-10.12.13'>
> [INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
> [INFO   ] [GL          ] OpenGL renderer <b'Intel HD Graphics 5000 OpenGL Engine'>
> [INFO   ] [GL          ] OpenGL parsed version: 2, 1
> [INFO   ] [GL          ] Shading version <b'1.20'>
> [INFO   ] [GL          ] Texture max size <16384>
> [INFO   ] [GL          ] Texture max units <16>
> [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
> [INFO   ] [Clipboard   ] Provider: pygame(['clipboard_nspaste'] ignored)
> [INFO   ] [OSC         ] using <multiprocessing> for socket
> [INFO   ] [Base        ] Start application main loop
> [INFO   ] [GL          ] NPOT texture support is available
> [WARNING] [Accordion   ] not enough space for displaying all children
> [WARNING] [Accordion   ] need 176px, got 100px
> [WARNING] [Accordion   ] layout aborted.
> [WARNING] [Accordion   ] not enough space for displaying all children
> [WARNING] [Accordion   ] need 220px, got 100px
> [WARNING] [Accordion   ] layout aborted.
> [ERROR  ] [WinPygame   ] unable to set icon
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/core/window/window_pygame.py", line 215, in set_icon
>     self._set_icon_standard(filename)
>   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/core/window/window_pygame.py", line 227, in _set_icon_standard
>     im = pygame.image.load(filename)
> pygame.error: File is not a Windows BMP file
> [INFO   ] [Context     ] Reloading graphics data...
> [INFO   ] [Context     ] Reloading done in 0.1481s
> [WARNING] [Accordion   ] not enough space for displaying all children
> [WARNING] [Accordion   ] need 220px, got 100px
> [WARNING] [Accordion   ] layout aborted.
>  Exception ignored in: 'kivy.graphics.context.Context.dealloc_texture'
>  OverflowError: signed integer is greater than maximum
>  Exception ignored in: 'kivy.graphics.context.Context.dealloc_texture'
>  OverflowError: signed integer is greater than maximum
>  Exception ignored in: 'kivy.graphics.context.Context.dealloc_texture'
>  OverflowError: signed integer is greater than maximum
> [WARNING] [Accordion   ] not enough space for displaying all children
> [WARNING] [Accordion   ] need 176px, got 100px
> [WARNING] [Accordion   ] layout aborted.
>  Exception ignored in: 'kivy.graphics.context.Context.dealloc_texture'
>  OverflowError: signed integer is greater than maximum

**Comment by aron-bordin** [comment]
Hi
You are using pygame (` [INFO ] [Window ] Provider: pygame`), and it's depreciated in kivy. You should be using sdl2.

Check the installation instructions here: https://kivy.org/docs/installation/installation-osx.html and a similar report: https://github.com/kivy/kivy-designer/issues/164

**Comment by antkowiakit** [comment]
Thanks for replay! Now i got this error:

> ➜  kivy-designer git:(master) python3 main.py
[INFO   ] [Logger      ] Record log in /Users/patryk/.kivy/logs/kivy_16-03-10_19.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
[INFO   ] [Factory     ] 179 symbols loaded
 Traceback (most recent call last):
   File "main.py", line 1, in <module>
     from designer.app import DesignerApp
   File "/Users/patryk/Downloads/kivy-designer/designer/app.py", line 8, in <module>
     from designer.add_file import AddFileDialog
   File "/Users/patryk/Downloads/kivy-designer/designer/add_file.py", line 4, in <module>
     from designer.helper_functions import ignore_proj_watcher
   File "/Users/patryk/Downloads/kivy-designer/designer/helper_functions.py", line 10, in <module>
     from kivy.app import App
   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/base.py", line 31, in <module>
     from kivy.lang import Builder
   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/lang/__init__.py", line 858, in <module>
     from kivy.lang.builder import Observable, Builder, BuilderBase, BuilderException
   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/lang/builder.py", line 17, in <module>
     from kivy.lang.parser import Parser, ParserException, _handlers, global_idmap,\
   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/kivy/lang/parser.py", line 21, in <module>
     from kivy.utils import rgba
 ImportError: cannot import name 'rgba'

**Comment by aron-bordin** [comment]
Hi,

Sorry for the delay, but there are some problems with your kivy installation. If you still facing this problem, please, remove kivy and do a fresh install on your env.

Thank you,
Aron
