### ISSUE TITLE
bug happens after i open a project

### ISSUE THREAD

**Issue by tsabi** [kivy/kivy-designer#201]
See attached screenshot. (because i cannot copy to clipboard it)
![kivy-designer-bug](https://cloud.githubusercontent.com/assets/210099/13812241/522ff580-eb7b-11e5-9527-d713983fb190.png)

As you see both self.cur_dir and command[3:] contains a valid directory. Joining them not produce valid directory.

**Comment by aron-bordin** [comment]
This bug is already reported here https://github.com/kivy/kivy-designer/issues/182 
I've seen some users getting this error, but I'm not able to reproducte it here... What is the language of  your system ?

**Comment by tsabi** [comment]
Hungarian.

**Comment by tsabi** [comment]
It can happen you cannot reproduce it, because there is a try/except block around the lines where the bug happens. You need to comment them out to not catch the exception.
