### ISSUE TITLE
Drag-drop inital widget out of the playground is not removing it in Kv

### ISSUE THREAD

**Issue by tito** [kivy/kivy-designer#23]
Step:
- create a new project, based on the floatlayout
- drag-drop the initial button outside the floatlayout
- the button stay in the KV, but it's removed from the floatlayout visually.

**Comment by gopar** [comment]
Mmm the same thing happens for any layout w/ any combo of widgets, at least for me it does.

**Comment by aron-bordin** [comment]
Hi, fixed in master.
