### ISSUE TITLE
ImportError during installation

### ISSUE THREAD

**Issue by DorKeinath** [kivy/kivy-designer#237]
# Problem
I couldn't start the designer:

`
...buildozer_spec_editor.py", line 18, in <module>
     from pygments.lexers.configs import IniLexer
 ImportError: No module named configs
`

# Solution
The problem was an old version of pygments (1.6), installed by Kivy using apt-get (python-pygments).
With pip I couldn't upgrade pygments ("owned by OS"). So I downloaded pygments as zip-File and used 

`
sudo python setup.py install
`

I'm not sure if this is a good solution. May be there is a less complicated way!? For noobies like me that's a pretty hard start for a new program, and I'm not sure everything is working now, because pip show says "... directory is not owned by the current user and the cache has been disabled."

# Environment info
kivy: 1.9.2-dev0
pygments: 1.6 - now 2.1.3
docutils: 0.11
watchdog: 0.8.3
jedi: 0.9.0
gitpython: 2.0.7
six: 1.10.0
kivy-garden: 0.1.4

Platform: Linux Mint 17.3 'Rosa' Mate 64-bit
Python: 2.7.5-5ubuntu3 and 3.4.0-0ubuntu2 (both nightly builds)

**Comment by aron-bordin** [comment]
Hi !

I updated the readme and docs, and now the pip command will download and update the necessary dependencies.

Thanks you for the contribution :+1:
