### ISSUE TITLE
Import problem during running

### ISSUE THREAD

**Issue by wavic** [kivy/kivy-designer#242]
Hello! When I run the program calling $ python main.py I get this:
`~/b/kivy-designer ❯❯❯ python main.py
[INFO   ] [Logger      ] Record log in /home/victor/.kivy/logs/kivy_16-08-19_6.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.1.3>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Haswell Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "main.py", line 1, in <module>
     from designer.app import DesignerApp
   File "/home/victor/bin/kivy-designer/designer/app.py", line 9, in <module>
     from designer.buildozer_spec_editor import BuildozerSpecEditor
   File "/home/victor/bin/kivy-designer/designer/buildozer_spec_editor.py", line 18, in <module>
     from pygments.lexers.configs import IniLexer
 ImportError: No module named configs
~/b/kivy-designer ❯❯❯     `
I have installed the requirements. Twise. Nothing.
I am using Ubuntu MInt.

**Comment by aron-bordin** [comment]
Hi,

There is some problem in pygments package on your system. Please, check this issue: https://github.com/kivy/kivy-designer/issues/133

**Comment by wavic** [comment]
I've removed pygmets. Because of dependencies kivy was removed too. I've installed pygments-2.1.3 via pip. Then again kivy. But kivy forced apt to download pygments-1.6 and install it. So I am stuck
