### ISSUE TITLE
ImportError: No module named filebrowser

### ISSUE THREAD

**Issue by shaun-ba** [kivy/kivy-designer#25]
Not sure what module this is depending on, i didn't see any dependencies in the installation readme

[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/kivy-designer/designer/app.py", line 17, in <module>
     from kivy.garden.filebrowser import FileBrowser
 ImportError: No module named filebrowser

**Comment by aswinramakrish** [comment]
@ly0 Thanks for the info. Your solution fixed the issue with FileBrowser. Although, I received an error with the ProjectLoader and so on. Pretty much ALL the garden modules (watchdog etc.)

I'm encountering this issue in OSX, is there a specific fix for that?

**Comment by butlernc** [comment]
Helped me! Thank you very much everyone!

**Comment by fr33co** [comment]
I change from filebrowser import FileBrowser in /kivy-designer/designer/add_file.py too

**Comment by randomelectrons** [comment]
I fixed this problem today by doing this:

1. kivy -m pip install -U watchdog pygments docutils jedi gitpython six kivy-garden
2. cd kivy-designer/
3. garden install --app filebrowser
4. kivy main.py
5. Celebrate

Note: I am using python 2.7 and kivy 1.9.1 on OS X El Capitan
