### ISSUE TITLE
setup issue, garden install filebrowser occur Error

### ISSUE THREAD

**Issue by pimier15** [kivy/kivy-designer#268]
garden install filebrowser

C:\Users\byoru>python.exe C:\Anaconda2\Scripts\garden install filebrowser
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\garden", line 28, in <module>
    garden_kivy_dir = abspath(join(dirname(kivy.__file__), 'garden'))
AttributeError: 'module' object has no attribute '__file__'

**Comment by KeyWeeUsr** [comment]
Most likely bad kivy installation or another file/folder named `kivy` in `C:\Users\byoru`. `__file__` means a path to the actual file, which for that line is `<somewhere>/site-packages/kivy/__init__.py`
