### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by modelorona** [kivy/kivy-designer#269]
I am getting a segmentation fault after running 

`python -m designer`

Everything up to this point installed fine i.e the dependencies and filebrowsers. 

I am trying to run it from a python 3.4 virtual environment on Ubuntu 14.04 and am using Kivy version 1.9.2.

I have attached a screenshot below showing the terminal output.
![seg_fault](https://cloud.githubusercontent.com/assets/23018759/21082325/7ad0ebf4-bfd1-11e6-9729-5d4157d79aec.png)

**Comment by aron-bordin** [comment]
There is some problem in the kivy installation, it's not related to Kivy Designer. Please, if you face this problem again, come to #kivy on IRC or use the forums to get some support on your installation.

Thanks :)

**Comment by DaleEMoore** [comment]
Ubuntu 16.04 fixed via:

# pushd /usr/lib/python3.5/lib-dynload/
# mkdir old
# mv readline* old

$ python3 -m designer

**Comment by Akash3194** [comment]
Thanx it worked
