### ISSUE TITLE
Wow, is kivy-designer ever in sad shape...

### ISSUE THREAD

**Issue by cinchent** [kivy/kivy-designer#280]
First, I tried installing onto Windows (latest version from repo).  It "runs", but practically everything I try -- even dragging the Screen object around in the UI Creator -- either fails outright, or crashes the designer entirely.  I have yet to discover _anything_ that actually fully works, frankly.  After saving a *very* primitive design, then it crashes upon subsequently reopening that design.  Definitely "Not Ready For Primetime" on that platform...

Next, I tried installing onto a RaspberryPi 3 (the platform I'm actually targeting), using an official RPi touchscreen display.  Here, it crashes at startup with a lengthy traceback, but since the crashed app has commandeered helm control, I can't click the Report Bug or Copy To Clipboard button.  I'm not going to manually retype the entire traceback, but the point-of-failure entry is (forgive any typos):
       :
    File "kivy/_clock.pyx", line 168, in kivy_clock.ClockEvent.tick (/tmp/pip-hLtZee-build/kivy/_clock.c:3530)
  TypeError: create_window() takes exactly 1 argument (2 given)
Really?  Something as basic as creating a window specifies the wrong number of args and wedges the tool?

Finally, figuring that all the implementers/maintainers are Linux-centric or -only, and that all the testing is done there, I fired up my Ubuntu 14.04 VM and installed it.  There, at least things didn't crash right and left, and basic functionality "works" (kinda, sorta, I guess, see below), but even things like simply trying to open the Project Settings dialog from the main menu crashes the app:
  pip.exceptions.InstallationError: Could not open requirements file ....
No, really.  There's the requrements.txt file, right there...  And this is with the latest "stable" build, installed following the documented instructions to the letter.

Even when things don't crash, they don't really "work".  Even something as simple as highlighting a widget then trying to Delete it, doesn't delete it.  Or perhaps I'm misusing this feature, in which case: a) it is incredibly non-intuitive, and b) there no actual documentation about how to do basic things like this in case there are subtleties I'm not hip to.

Um, I'd really like to buy in to the promise of what kivy-designer intends to be.  It's a great idea!  Most of my Python GUI work over the years has been using PySide/PyQt and PyGtk/PyGObject, and in those toolchains Qt-designer and glade are indispensable.  I'm surprised and disappointed that kivy-designer is not in a further state of evolution.  This should be a really cool, simple, intuitive, (even reasonably) stable app.  But... it's not.  If I had the time, and wasn't already working four projects, I'd volunteer to move this along up the food chain a little...

This is not a troll, this is an exhortation to Do Better Work.  As it is now, in the state it's in, it shouldn't be seeing the light of day.

**Comment by inclement** [comment]
Kivy Designer is essentially unmaintained and was never released. I didn't realise that the README doesn't make this clear, and I'll push a change to fix that.

The project is publicly available because it's open code and it does attract some small contributions. What it really needs is a maintainer able to dedicate serious effort to it, but none of the Kivy core maintainers have been able to do so due to other time constraints and other priorities. It's maybe worth noting that one reason for this neglect is that the core developers mostly don't find a major need for such a tool, especially considering the major effort that would be needed to make it anywhere near as flexible as kv language. We do appreciate that some users would like it, which is why its development was started even if if hasn't been able to reach a stable state.

**Comment by cinchent** [comment]
Thanks for the clarification, @inclement.  I wouldn't have been so harsh in my critique if these working presumptions were made clear.  Given the focus on polishing the documentation and many app features that are "niceties" when even basic core functionality is fundamentally broken, I naturally came to the conclusion that this was much further along toward productization.

>> It's maybe worth noting that one reason for this neglect is that the core developers mostly don't find a major need for such a tool, especially considering the major effort that would be needed to make it anywhere near as flexible as kv language.

Having done GUIs for commercial products over the last 15 years, I can personally attest to the idea that, on the contrary, a designer tool is extremely valuable.  Yes, 'kv' is more flexible.  But flexibility is only one attribute of many in a highly usable toolchain such as GTK+ or Qt, which Kivy should rightly aspire to match and surpass.  If I have to write "code" -- albeit in a mostly descriptive language like kv -- to position and provision every widget in my conventional GUI app, my productivity plummets in comparison to a workflow that incorporates a pseudo-WYSIWYG tool like a designer.  (Hardware designers will confirm the same -- you don't see them rushing out to replace their schematic capture and board layout tools with others that would require them to represent their designs in "code".)

Besides, however powerful and flexible a language kv may be or become, it is no match for the power and flexibility of Python itself, nor should it try to be.  Separating the View from the Controller should be the whole point here, and confining kv to a view-like operation space is fine.  Anything that improves on CSS as an expressive vehicle in this regard is a step in the right direction.

Anyway, in the absence of an evolved Kivy Designer, and not having the time myself to devote to its progression, I am halfway inclined to create a stopgap tool that would take the XML output emitted from an existing tool like qt-designer or glade, and morph it into a kv description.  That would be a much simpler first step that could yield the benefits of having a more mature designer tool without the enormous effort required to polish the creation of another one, or wait on others to do so.  If I do so, I will be sure to share it.
