### ISSUE TITLE
save project to named folder

### ISSUE THREAD

**Issue by MysticMight** [kivy/kivy-designer#286]
Folder name is ignored in path at [app.py#L1055](https://github.com/kivy/kivy-designer/blob/master/designer/app.py#L1055). 
Code for both list_view and icon_view should include `instance.filename` at the end of path.

Also note that another path `instance.path` exists. Could this be used instead of the one from a specific view widget?

**Comment by aron-bordin** [comment]
this was replaced by the new "FileBrowser" widget. Thank you for reporting ;)
