### ISSUE TITLE
filebrowser installed via garden not visible to kivy-designer

### ISSUE THREAD

**Issue by sarimak** [kivy/kivy-designer#32]
Installed filebrowser using
> python2 ./garden install filebrowser
as described in kivy-designer README.

After running
> python2 main.py
to start the designer, import error at line 17 in main.py indicates that filebrowser module could not be found.

Workaround: As root, copy libs/garden/garden.filebrowser/__init__.py to /usr/local/lib/python2.7/dist-packages/Kivy-1.8.0*/kivy/garden/filebrowser.py
and
touch __init__.py
in the same directory.

Then kivy-designer runs fine and filebrowser is correctly imported.
(I also have changed kivy.require from 1.4.0 to 1.8.0 in designer's app.py for sure).

**Comment by nenodias** [comment]
Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/home/mylocal/framework/kivy-designer/designer/app.py", line 18, in <module>
     from kivy.garden.filebrowser import FileBrowser
 ImportError: No module named filebrowser

**Comment by dessant** [comment]
I can't reporduce this anymore, please reopen if you still have this issue.

**Comment by riccitensor** [comment]
I have the same problem here -- https://github.com/kivy/kivy/issues/4177
