### ISSUE TITLE
Not able to install on windows

### ISSUE THREAD

**Issue by pkor** [kivy/kivy-designer#34]
I followed the directions for installing this and can't get it to work. First I couldn't get the garden to install the filebrowser so I manually downloaded it, made a garden directory and placed it there. Now it gives me an error saying it can't find the module 'watchdog.events'. I have watchdog installed but it can't find it for some reason. Any tips?

**Comment by dessant** [comment]
After installing every dep from `requirements.txt` in the new gsoc branch, it works.
