### ISSUE TITLE
very strange-looking on osx mavericks

### ISSUE THREAD

**Issue by batwicket** [kivy/kivy-designer#38]
It seems to run, but the GUI looks very strange. I don't think it's specific to the gui-designer because the examples also look like this.

![screen shot 2014-03-06 at 12 47 34 pm](https://f.cloud.github.com/assets/6760834/2350443/9895d114-a570-11e3-93de-22f7e7a1111e.png)

**Comment by dessant** [comment]
On OS X the sdl2 image provider is used be default, please reopen if you still have this issue.
