### ISSUE TITLE
Fatal Python error: (pygame parachute) Segmentation Fault

### ISSUE THREAD

**Issue by ever4cyth** [kivy/kivy-designer#60]
python main.py 
[INFO   ] [Logger      ] Record log in /home/magnolia/.kivy/logs/kivy_14-10-06_5.txt
[INFO   ] Kivy v1.9.0-dev
[INFO   ] [Python      ] v2.7.3 (default, Feb 27 2014, 19:58:35) 
[GCC 4.6.3]
[INFO   ] [Factory     ] 171 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[WARNING] [WinPygame   ] Video: failed (multisamples=2)
[WARNING] [WinPygame   ] trying without antialiasing
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 8.0.4>
[INFO   ] [GL          ] OpenGL vendor <Tungsten Graphics, Inc>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Sandybridge Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame(['text_sdl2'] ignored)
[WARNING] Call to deprecated function __call__ in /home/magnolia/kivy/lib/python2.7/site-packages/kivy/utils.py line 246.Called from /home/magnolia/.kivy/garden/garden.filebrowser/__init__.py line 80 by <module>().
[WARNING] Call to deprecated function __call__ in /home/magnolia/kivy/lib/python2.7/site-packages/kivy/utils.py line 246.Called from /home/magnolia/kivy/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_sdl2.py line 10 by <module>().
[INFO   ] [Clipboard   ] Provider: pygame(['clipboard_sdl2'] ignored)
Fatal Python error: (pygame parachute) Segmentation Fault
Aborted (core dumped)

Thought it is due to pygame issue as discussed in other forum, but pygame seems fine.

python
Python 2.7.3 (default, Feb 27 2014, 19:58:35) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
>>> pygame.__file__
'/usr/lib/python2.7/dist-packages/pygame/__init__.pyc'
>>> pygame.init()
(6, 0)
>>> pygame.display.set_mode((640,480), pygame.OPENGL)
<Surface(640x480x32 SW)>
>>> quit()

**Comment by kived** [comment]
Please update to the newest stable version of Kivy 1.9.0. We now use SDL2 instead of Pygame by default (though Pygame is still available as a fallback, and will be used if you compile Kivy without SDL2 libraries). The PPA version of Kivy uses SDL2 only.

If you still have this (or any) problem with Kivy 1.9.0, please open a new issue.
