### ISSUE TITLE
doesnot run app

### ISSUE THREAD

**Issue by qmmp123** [kivy/kivy-designer#63]
I enter in terminal 
python main.py
and then i get 
[WARNING] Call to deprecated function __call__ in /usr/lib/python3.4/site-packages/kivy/utils.py line 252.Called from /home/lantlord/.kivy/garden/garden.filebrowser/__init__.py line 80 by <module>().
[INFO   ] [Clipboard   ] Provider: pygame(['clipboard_dbusklipper'] ignored)
 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/home/lantlord/develop/kivy-designer/designer/app.py", line 34, in <module>
     from designer.project_loader import ProjectLoader, ProjectLoaderException
   File "/home/lantlord/develop/kivy-designer/designer/project_loader.py", line 164
     exec py_string in module.__dict__
                  ^
 SyntaxError: Missing parentheses in call to 'exec'

**Comment by tito** [comment]
Use python 2.7, designer is not maintained by us, and does not work with Python 3.x :(

**Comment by qmmp123** [comment]
Tnank you. when will you make app for python 3?

**Comment by aron-bordin** [comment]
Hi @qmmp123 
I'm working with Python3 support, It'll be running soon :)
