### ISSUE TITLE
WARNING:: This software was part of GSOC 2013, and searching for a maintainer.

### ISSUE THREAD

**Issue by auvipy** [kivy/kivy-designer#65]
what does this message for? isn't there any maintainer for this?

**Comment by tito** [comment]
No, unfortunately, there is no official maintainer. We (as kivy core dev) cannot manage this tool as well, we're already overwhelmed by all the subproject.

If anybody want to continue the work and manage it, it would be very welcomed :)

**Comment by auvipy** [comment]
I'm interested

**Comment by tito** [comment]
Come over #kivy-dev on irc to discuss a little bit about it :)

**Comment by nicklasb** [comment]
Well, was there any dicussion? Not saying I will maintain it, just wondering. :-)

**Comment by inclement** [comment]
I don't remember any discussion arising directly from this, but it is possible that there will be another Kivy Designer GSOC project this year with the goal of making it much more immediately usable, hopefully raising interest, and potentially making it easier to find maintainers.

**Comment by nicklasb** [comment]
Ok. To me it is difficult to understand why that would be difficult. 
I used to develop application using Delphi and having a dedicated GUI for UI development is *way* faster than doing it in code, they have cross platform code and uses preview styles for different platforms.

I will have a look later on and see if can't at least contribute to it.

**Comment by dessant** [comment]
@auvipy @nicklasb luckily we have a gsoc student assigned for this project, but contributions are very welcome regardless. Feel free to ask questions (#kivy-dev on freenode) and submit PRs.

**Comment by nicklasb** [comment]
Good stuff.
I know that many of PyCharm's users (including me), want better Kivy support, perhaps there is some kind of common interest there. 
I mean, if they'd like to integrate kivy-designer into PyCharm, perhaps they could be interested in contributing to this.

**Comment by dessant** [comment]
@nicklasb We've come forward and asked them, their team is welcoming and agreed to add Kivy support, it mostly depends on someone writing the code, https://github.com/kivy/kivy/issues/2717.
Please post on that issue if you want to do it or you know someone who would make this contribution for PyCharm.

When this step is done, we could think about even tighter integration.

**Comment by nicklasb** [comment]
Great! 
I am not a java developer, and also, I am a customer that thinks that it would benefit JetBrains commercially to have a good Kivy integration. 
I would think that they have reason in investing a little of their own resources to make it happen.

**Comment by dessant** [comment]
Our last GSOC student is currently maintaining KD, but prs are welcome from anybody regardless of this. ;)
