### ISSUE TITLE
files and folders not detected correctly

### ISSUE THREAD

**Issue by YK2** [kivy/kivy-designer#67]
﻿[Administrator@C kivy-designer-master]>> "C:\Users\Administrator\Kivy-1.8.0-py2.7-win32\Python27\python.exe" "C:\Users\Administrator\kivy-designer-master\apps\origional\test1\main.py" 
The system cannot find the file specified < "C:\Users\Administrator\Kivy-1.8.0-py2.7-win32\Python27\python.exe" "C:\Users\Administrator\kivy-designer-master\apps\origional\test1\main.py"  >

i have created folders for a app test and when i try to run the project the above error is given, this also happens when i try to run the project from its default location of appdata\roaming\test1\main.py, other folders show up in filebrowser but appdata does not

however if i navigate to the folder itself and run the main.py from there is runs, again i hope someone can help

tnx

**Comment by aron-bordin** [comment]
Hi!  thank you for reporting this bug. project_loader(a class responsible for managing files) was completely re-implemented. If you face a similar bug again, please, open a new issue about it.
