### ISSUE TITLE
i cant open kivy-designer window

### ISSUE THREAD

**Issue by RezaOptic** [kivy/kivy-designer#74]
pip install watchdog

Requirement already satisfied (use --upgrade to upgrade): watchdog in d:\softwar
e\python\kivy-1.9.0-py3.4-win32-x86\python34\lib\site-packages

pip install pygments

Requirement already satisfied (use --upgrade to upgrade): pygments in d:\softwar
e\python\kivy-1.9.0-py3.4-win32-x86\python34\lib\site-packages

pip install docutils

Requirement already satisfied (use --upgrade to upgrade): docutils in d:\softwar
e\python\kivy-1.9.0-py3.4-win32-x86\python34\lib\site-packages

pip install kivy-garden

Requirement already satisfied (use --upgrade to upgrade): kivy-garden in d:\soft
ware\python\kivy-1.9.0-py3.4-win32-x86\python34\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): requests in d:\softwar
e\python\kivy-1.9.0-py3.4-win32-x86\python34\lib\site-packages (from kivy-garden
)
garden install filebrowser

Garden package already installed in C:\Users\RezaOPTIC\.kivy\garden\garden.fileb
rowser
Use --upgrade to upgrade.

everything is correct ????????????????????????????
After 
I type python main.py and i take this error 

botstrapping Kivy @ D:\SoftWare\Python\Kivy-1.9.0-py3.4-win32-x86\ with Python D
:\SoftWare\Python\Kivy-1.9.0-py3.4-win32-x86\Python34
done bootstraping kivy...have fun!\n
running "python.exe main.py" \n
[INFO              ] [Logger      ] Record log in C:\Users\RezaOPTIC\.kivy\logs\
kivy_15-05-07_69.txt
[INFO              ] [Kivy        ] v1.9.0
[INFO              ] [Python      ] v3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22
:43:06) [MSC v.1600 32 bit (Intel)]
[INFO              ] [Factory     ] 173 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sd
l2, img_pil (img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <b'2.1.0 - Build 8.15.10.2246
'>
[INFO              ] [GL          ] OpenGL vendor <b'Intel'>
[INFO              ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics'>
[INFO              ] [GL          ] OpenGL parsed version: 2, 1
[INFO              ] [GL          ] Shading version <b'1.20  - Intel Build 8.15.
10.2246'>
[INFO              ] [GL          ] Texture max size <4096>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Shader      ] fragment shader: <b'No errors.'>
[INFO              ] [Shader      ] vertex shader: <b'No errors.'>
[INFO              ] [Shader      ] program: <No errors.>
[INFO              ] [Window      ] auto add sdl2 input provider
libpng warning: iCCP: known incorrect sRGB profile
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, n
ot docked
[INFO              ] [Text        ] Provider: sdl2
[WARNING           ] [Call to deprecated function __call__ in D]\SoftWare\Python
\Kivy-1.9.0-py3.4-win32-x86\kivy34\kivy\utils.py line 251.Called from C:\Users\R
ezaOPTIC\.kivy\garden\garden.filebrowser\__init__.py line 80 by <module>().
[INFO              ] [Clipboard   ] Provider: winctypes
 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "D:\SoftWare\Python\Kivy-1.9.0-py3.4-win32-x86\kivy-designer\designer\ap
p.py", line 34, in <module>
     from designer.project_loader import ProjectLoader, ProjectLoaderException
   File "D:\SoftWare\Python\Kivy-1.9.0-py3.4-win32-x86\kivy-designer\designer\pr
oject_loader.py", line 164
     exec py_string in module.__dict__
                  ^
 SyntaxError: Missing parentheses in call to 'exec'

this error and i cant open the kivy-designer window .
why?

**Comment by aron-bordin** [comment]
Hi @RezaOptic 
The Kivy Designer is not yet compatible with Python 3, re-install the requirements and try to use it with Python2.

**Comment by inclement** [comment]
We could have a 'support python3' issue if there isn't one already, this is an important goal, but I've closed this issue as now representing that directly.

**Comment by kived** [comment]
It's an important long-term goal, though you shouldn't expect Python 3 support immediately - use Python 2 for now. Issue added as #75.
